export const DEFAULT_SESSION_EXPIRY_DURATION_IN_DAYS = process.env
  .DEFAULT_SESSION_EXPIRY_DURATION_IN_DAYS
  ? parseInt(process.env.DEFAULT_SESSION_EXPIRY_DURATION_IN_DAYS, 10)
  : 1;

export const DYNAMO_DB_REGION = process.env.DYNAMO_DB_REGION || "";
export const DYNAMO_DB_TABLE_NAME = process.env.DYNAMO_DB_TABLE_NAME || "";
export const DYNAMODB_CUSTOMER_SEARCH_INDEX =
  process.env.DYNAMODB_CUSTOMER_SEARCH_INDEX || "";

export const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY || "";

export const REMEMBER_ME_SESSION_EXPIRY_DURATION_IN_DAYS = process.env
  .REMEMBER_ME_SESSION_EXPIRY_DURATION_IN_DAYS
  ? parseInt(process.env.REMEMBER_ME_SESSION_EXPIRY_DURATION_IN_DAYS, 10)
  : 30;
