import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import SideNavigation from "./components/ui/side-navigation/side-navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen flex"}>
        <div className="flex flex-1">
          <SideNavigation />
          <div className="flex-1">
            <main className="flex justify-center px-6">
              <div className="container">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
