import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-center py-3 bg-green-700 drop-shadow-md">
          <div className="flex items-end gap-5 container">
            <Image width="110" height="72" src="/main-logo.png" alt="Seymour Mowing & Maintenance" />
            <h1 className="text-3xl text-white font-bold uppercase">Seymour Mowing & Maintenance</h1>
          </div>
        </header>
        <main className="flex justify-center p-3">
          <div className="container">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
