import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import SideNavigation from "./components/ui/side-navigation/side-navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " h-screen flex bg-green-100"}>
        <div className="flex justify-center flex-1">
          <SideNavigation />
          <div className="flex-1 bg-slate-200 shadow-xl">
            <div className="h-[60px] px-6 py-2 border-b bg-white border-b-slate-300">

            </div>
            <main className="px-6">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
