export const DEFAULT_SESSION_EXPIRY_DURATION_IN_DAYS = process.env
  .DEFAULT_SESSION_EXPIRY_DURATION_IN_DAYS
  ? parseInt(process.env.DEFAULT_SESSION_EXPIRY_DURATION_IN_DAYS, 10)
  : 1;

export const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY || "";

export const REMEMBER_ME_SESSION_EXPIRY_DURATION_IN_DAYS = process.env
  .REMEMBER_ME_SESSION_EXPIRY_DURATION_IN_DAYS
  ? parseInt(process.env.REMEMBER_ME_SESSION_EXPIRY_DURATION_IN_DAYS, 10)
  : 30;
